version: 2
updates:

- package-ecosystem: 'npm'
  directory: '/'
  schedule:
    interval: 'monthly'
    time: '05:00'

- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'monthly'
    time: '05:00'
